dist: bionic
sudo: false
language: c

branches:
  only:
    - master
    - /^v[\d.-]+$/

cache:
  directories:
    - $HOME/env

notifications:
  email: false

before_install:
  - pip install --user hererocks
  - hererocks $HOME/env --luajit 2.0.3 --luarocks latest
  - source $HOME/env/bin/activate

install:
  - luarocks show lanes > /dev/null || luarocks install lanes
  - luarocks show luacheck > /dev/null || luarocks install luacheck
  - luarocks list --outdated --porcelain | awk '{ print $1, $3 }' | xargs --no-run-if-empty -n 2 luarocks install

script:
  - git diff --check $TRAVIS_COMMIT_RANGE
  - git diff --name-only $TRAVIS_COMMIT_RANGE | grep '\.lua$' | grep -v '^lua/entities/gmod_wire_expression2/core/' | xargs --no-run-if-empty luacheck
  - luacheck .luacheckrc

before_deploy:
  - curl -L "https://github.com/wiremod/gmad-build/releases/latest/download/gmad_linux" -o "$HOME/gmad_linux"
  - chmod +x "$HOME/gmad_linux"
  - $HOME/gmad_linux create -folder . -out wiremod.gma

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EK1zfysVaXMB52mfDlPFwaqM7zGJE/G1iFKyjWMV20GDqZkE9/g+KlwwaRuz7q0NX0KgGuc7dk5j0JQXTg3Z14kUYdIYSq3tDkp0YBeePqVGUgQoA19ZFPlBdZEV0EF3dDHMYmErNYBuCYW7Twrzy++WgzghCcthXaV9jboF5lk=
  file: wiremod.gma
  on:
    repo: wiremod/wire
    tags: true